corrections=DO_NOT_LOOK/
alumni=../Lucie/

CC=gcc

#CFLAGS=-Wextra -Werror -Wall
compile_and_run_C00ex00: ${corrections}C00/ex00/ft_putchar.c ${alumni}C00/ex00/ft_putchar.c
	${CC} $^ -o ${corrections}C00/ex00/main ${corrections}C00/ex00/main.c ${CFLAGS}
	./${corrections}C00/ex00/main

compile_and_run_C00ex01: ${corrections}C00/ex01/ft_print_alphabet.c ${alumni}C00/ex01/ft_print_alphabet.c
	${CC} $^ -o ${corrections}C00/ex01/main ${corrections}C00/ex01/main.c ${CFLAGS}
	./${corrections}C00/ex01/main

compile_and_run_C00ex02: ${corrections}C00/ex02/ft_print_reverse_alphabet.c ${alumni}C00/ex02/ft_print_reverse_alphabet.c
	${CC} $^ -o ${corrections}C00/ex02/main ${corrections}C00/ex02/main.c ${CFLAGS}
	./${corrections}C00/ex02/main

compile_and_run_C00ex03: ${corrections}C00/ex03/correction.c ${alumni}C00/ex03/ft_print_numbers.c
	${CC} $^ -o ${corrections}C00/ex03/main ${corrections}C00/ex03/main.c ${CFLAGS}
	./${corrections}C00/ex03/main

compile_and_run_C00ex04: ${corrections}C00/ex04/correction.c ${alumni}C00/ex04/ft_is_negative.c
	${CC} $^ -o ${corrections}C00/ex04/main ${corrections}C00/ex04/main.c ${CFLAGS}
	./${corrections}C00/ex04/main

compile_and_run_C00ex05: ${corrections}C00/ex05/correction.c ${alumni}C00/ex05/ft_print_comb.c
	${CC} $^ -o ${corrections}C00/ex05/main ${corrections}C00/ex05/main.c ${CFLAGS}
	./${corrections}C00/ex05/main

compile_and_run_C00ex06: ${corrections}C00/ex06/correction.c ${alumni}C00/ex06/ft_print_comb2.c
	${CC} $^ -o ${corrections}C00/ex06/main ${corrections}C00/ex06/main.c ${CFLAGS}
	./${corrections}C00/ex06/main

compile_and_run_C00ex07: ${corrections}C00/ex07/correction.c ${alumni}C00/ex07/ft_putnbr.c
	${CC} $^ -o ${corrections}C00/ex07/main ${corrections}C00/ex07/main.c ${CFLAGS}
	./${corrections}C00/ex07/main

compile_and_run_C00ex08: ${corrections}C00/ex08/correction.c ${alumni}C00/ex08/ft_print_combn.c
	${CC} $^ -o ${corrections}C00/ex08/main ${corrections}C00/ex08/main.c ${CFLAGS}
	./${corrections}C00/ex08/main