corrections=DO_NOT_LOOK/
alumni=../Lucie/

CC=gcc
#CFLAGS=-Wextra -Werror -Wall

compile_and_run_c00ex00: ${corrections}ex00/ft_putchar.c ${alumni}ex00/ft_putchar.c
	${CC} $^ -o ${corrections}ex00/main ${corrections}ex00/main.c ${CFLAGS}
	./${corrections}ex00/main

compile_and_run_c00ex01: ${corrections}ex01/ft_print_alphabet.c ${alumni}ex01/ft_print_alphabet.c
	${CC} $^ -o ${corrections}ex01/main ${corrections}ex01/main.c ${CFLAGS}
	./${corrections}ex01/main

compile_and_run_c00ex02: ${corrections}ex02/ft_print_reverse_alphabet.c ${alumni}ex02/ft_print_reverse_alphabet.c
	${CC} $^ -o ${corrections}ex02/main ${corrections}ex02/main.c ${CFLAGS}
	./${corrections}ex02/main

compile_and_run_c00ex03: ${corrections}ex03/correction.c ${alumni}ex03/ft_print_numbers.c
	${CC} $^ -o ${corrections}ex03/main ${corrections}ex03/main.c ${CFLAGS}
	./${corrections}ex03/main

compile_and_run_c00ex04: ${corrections}ex04/correction.c ${alumni}ex04/ft_is_negative.c
	${CC} $^ -o ${corrections}ex04/main ${corrections}ex04/main.c ${CFLAGS}
	./${corrections}ex04/main

compile_and_run_c00ex05: ${corrections}ex05/correction.c ${alumni}ex05/ft_print_comb.c
	${CC} $^ -o ${corrections}ex05/main ${corrections}ex05/main.c ${CFLAGS}
	./${corrections}ex05/main

compile_and_run_c00ex06: ${corrections}ex06/correction.c ${alumni}ex06/ft_print_comb2.c
	${CC} $^ -o ${corrections}ex06/main ${corrections}ex06/main.c ${CFLAGS}
	./${corrections}ex06/main

compile_and_run_c00ex07: ${corrections}ex07/correction.c ${alumni}ex07/ft_putnbr.c
	${CC} $^ -o ${corrections}ex07/main ${corrections}ex07/main.c ${CFLAGS}
	./${corrections}ex07/main

compile_and_run_c00ex08: ${corrections}ex08/correction.c ${alumni}ex08/ft_print_combn.c
	${CC} $^ -o ${corrections}ex08/main ${corrections}ex08/main.c ${CFLAGS}
	./${corrections}ex08/main